"""Fix username column in posts table

Revision ID: 06ed79bfe2d8
Revises: 2d6812cfbcf8
Create Date: 2024-12-17 14:43:07.517534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ed79bfe2d8'
down_revision: Union[str, None] = '2d6812cfbcf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('userName', sa.String(), nullable=False))
    op.drop_column('comments', 'user_name')
    op.add_column('posts', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('posts', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'username')
    op.add_column('comments', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'userName')
    # ### end Alembic commands ###
