"""changed sername to lowercase

Revision ID: 56e943f4ec84
Revises: 06ed79bfe2d8
Create Date: 2024-12-17 14:52:39.155651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e943f4ec84'
down_revision: Union[str, None] = '06ed79bfe2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('comments', 'userName')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('userName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
